name: Refresh Assets

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

permissions:
  contents: write

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm run build

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "refresh assets"
          file_pattern: assets/core_v1.json assets/version.json
